import { useState } from "react";
import {
  Alert,
  Avatar,
  Box,
  Container,
  IconButton,
  Snackbar,
  Typography
} from "@mui/material";
import Head from "next/head";
import TodoForm from "../components/TodoForm";
import TodoList from "../components/TodoList";
import { TodoContext } from "./TodoContext";
import { useAuth } from "../Auth";
import Loading from "../components/Loading";
import Login from "../components/Login";
import { auth, db } from "../firebase";
import { collection, getDocs, where, query, orderBy } from "firebase/firestore";
import { verifyIdToken } from "../firebaseAdmin";
import nookies from "nookies";

// https://www.youtube.com/watch?v=exGtoyzy8Vo  LINK TO COURSE

export default function Home({ todosProps }) {
  console.log(todosProps);
  const [open, setOpen] = useState(false);
  const [alertType, setAlertType] = useState("success");
  const [alertMessage, setAlertMessage] = useState("");
  const [todo, setTodo] = useState({ title: "", detail: "" });

  const { currentUser, loading } = useAuth();

  console.log("User: ", currentUser);

  const showAlert = (type, msg) => {
    setAlertType(type);
    setAlertMessage(msg);
    setOpen(true);
  };

  const handleClose = (event, reason) => {
    if (reason === "clickaway") {
      return;
    }

    setOpen(false);
  };
  if (!currentUser) {
    return <Login />;
  }
  if (loading) {
    return <Loading type="bubbles" color="yellowgreen" />;
  }
  // return <Login />;
  // return <Loading type="bubbles" color="yellowgreen" />;
  return (
    <TodoContext.Provider value={{ showAlert, todo, setTodo }}>
      <Head>
        <title>Todo - Firebase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth={"sm"}>
        <Box sx={{ display: "flex", justifyContent: "space-between" }} mt={3}>
          <IconButton onClick={() => auth.signOut()}>
            <Avatar src={currentUser.photoURL} />
          </IconButton>
          <Typography variant="h5">{currentUser.displayName}</Typography>
        </Box>
        <TodoForm />

        <Snackbar
          open={open}
          autoHideDuration={2000}
          onClose={handleClose}
          anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
        >
          <Alert
            onClose={handleClose}
            severity={alertType}
            sx={{ width: "100%" }}
          >
            {alertMessage}
          </Alert>
        </Snackbar>
        <TodoList todosProps={todosProps} />
      </Container>
    </TodoContext.Provider>
  );
}

export async function getServerSideProps(context) {
  try {
    const cookies = nookies.get(context);
    const token = await verifyIdToken(cookies.token);
    const { email } = token;
    console.log("Email: ", email);
    const collectionRef = collection(db, "todos");
    const q = query(
      collectionRef,
      where("email", "==", email),
      orderBy("timestamp", "desc")
    );
    console.log(q);
    const querySnapshot = await getDocs(q);
    let todos = [];
    querySnapshot.forEach(doc => {
      todos.push({
        ...doc.data(),
        id: doc.id,
        timestamp: doc.data().timestamp.toDate().getTime()
      });
      console.log("DOC: ", doc);
    });
    return {
      props: {
        todosProps: JSON.stringify(todos) || []
      }
    };
  } catch (error) {
    return { props: {} };
  }
}
